# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: example.com
  tag: 0.0.1
  pullPolicy: IfNotPresent
  registrySecret: secret_name

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.org/mergeable-ingress-type: minion
  path: /
  tls: []
#    - secretName: chart-example-tls
#      hosts:
#        - chart-example.local
resources:
   limits:
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 64Mi
env:
  TZ: Europe/Moscow
  LANG: en_US.UTF-8
  SENTRY_DSN:
  SECRET_KEY:

nodeSelector: {}

tolerations: []

affinity: {}
