apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "project.fullname" . }}-migrate
  labels:
    app: {{ include "project.name" . }}
    release: {{ .Release.Name }}
    tier: migrate
    chart: {{ include "project.chart" . }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ include "project.name" . }}
        release: {{ .Release.Name }}
        tier: migrate
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Values.image.registrySecret }}
      containers:
      - name: migrate-job
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: []
        args:
          - python
          - manage.py
          - migrate
        env:
          {{- range $key, $val := .Values.env }}
          - name:   {{ $key }}
            value:  {{ $val | quote }}
          {{- end }}
